apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: import-flow-bwce-api
  title: Import flow for BWCE projects with api
  description: Import existing BWCE APIs into TIBCO Developer Hub
  tags:
    - import-flow
    - tibco
    - template
    - developer-hub
spec:
  owner: group:default/tibco-imported
  type: import-flow

  parameters:
    - title: Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: GitHub repository with Existing BWCE Project
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

    - title: Fill in some steps
      required:
        - application
        - owner
      properties:
        apijsonlocation:
          title: api json location
          type: string
          description: to change
        application:
          title: BWCE Application
          type: string
          description: Name of the BWCE Application to import
        owner:
          title: Owner
          type: string
          description: Owner of the template
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

# The import flow consist out of 4 steps:
# 1. Fetch the project from GitHub
# 2. Generate the Component YAML
# 3. Commit the Component YAML file back to the GitHub project branch creating a pull request
# 4. Register the Component in the catalog

 
